import { Display } from 'src/app/model/DataSelection/Profile/Display'
import { Translation } from 'src/app/model/DataSelection/Profile/Translation'
import { ProfileEntryDetails } from 'src/app/model/Search/SearchDetails/ProfileEntryDetails'
import { ProfileEntryRelative } from 'src/app/model/Search/SearchDetails/ProfileEntryRelative'

const createDisplay = (value: string): Display =>
  new Display([new Translation('de-DE', value), new Translation('en-US', value)], value)

export function createTestProfileEntryDetails(): ProfileEntryDetails[] {
  const profiles = [
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose',
      name: 'MII PR Diagnose Condition',
      module: 'Diagnose',
      fields: [
        'Condition',
        'identifier',
        'clinicalStatus',
        'verificationStatus',
        'category',
        'severity',
        'code',
        'bodySite',
        'subject',
        'encounter',
        'onset',
        'recordedDate',
        'note',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/core/modul-prozedur/StructureDefinition/Procedure',
      name: 'MII PR Prozedur Procedure',
      module: 'Prozedur',
      fields: [
        'Procedure',
        'identifier',
        'status',
        'category',
        'code',
        'subject',
        'encounter',
        'performed',
        'performer',
        'bodySite',
        'note',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/Vitalstatus',
      name: 'MII PR Person Vitalstatus',
      module: 'Person',
      fields: [
        'Observation',
        'identifier',
        'status',
        'category',
        'code',
        'subject',
        'encounter',
        'effective',
        'value',
        'note',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/Todesursache',
      name: 'MII PR Person Todesursache',
      module: 'Person',
      fields: [
        'Condition',
        'identifier',
        'clinicalStatus',
        'verificationStatus',
        'category',
        'code',
        'subject',
        'encounter',
        'recordedDate',
        'note',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/DiagnosticReportLab',
      name: 'MII PR Labor Laborbefund',
      module: 'Labor',
      fields: [
        'DiagnosticReport',
        'identifier',
        'status',
        'category',
        'code',
        'subject',
        'encounter',
        'effective',
        'issued',
        'performer',
        'specimen',
        'result',
        'conclusion',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab',
      name: 'MII PR Labor Laboruntersuchung',
      module: 'Labor',
      fields: [
        'Observation',
        'identifier',
        'status',
        'category',
        'code',
        'subject',
        'encounter',
        'effective',
        'issued',
        'value',
        'interpretation',
        'specimen',
        'referenceRange',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ServiceRequestLab',
      name: 'MII PR Labor Laboranforderung',
      module: 'Labor',
      fields: [
        'ServiceRequest',
        'identifier',
        'status',
        'intent',
        'category',
        'priority',
        'code',
        'subject',
        'encounter',
        'authoredOn',
        'requester',
        'specimen',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationRequest',
      name: 'MII PR Medikation MedicationRequest',
      module: 'Medikation',
      fields: [
        'MedicationRequest',
        'identifier',
        'status',
        'intent',
        'category',
        'priority',
        'medication',
        'subject',
        'encounter',
        'authoredOn',
        'requester',
        'reasonCode',
        'dosageInstruction',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement',
      name: 'MII PR Medikation MedicationStatement',
      module: 'Medikation',
      fields: [
        'MedicationStatement',
        'identifier',
        'status',
        'category',
        'medication',
        'subject',
        'context',
        'effective',
        'dateAsserted',
        'reasonCode',
        'note',
        'dosage',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/medikationsliste',
      name: 'MII PR Medikation Medikationsliste',
      module: 'Medikation',
      fields: [
        'List',
        'identifier',
        'status',
        'mode',
        'title',
        'code',
        'subject',
        'encounter',
        'date',
        'entry',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication',
      name: 'MII PR Medikation Medication',
      module: 'Medikation',
      fields: [
        'Medication',
        'identifier',
        'code',
        'status',
        'manufacturer',
        'form',
        'amount',
        'ingredient',
        'batch',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration',
      name: 'MII PR Medikation MedicationAdministration',
      module: 'Medikation',
      fields: [
        'MedicationAdministration',
        'identifier',
        'status',
        'category',
        'medication',
        'subject',
        'context',
        'effective',
        'performer',
        'reasonCode',
        'request',
        'dosage',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/core/modul-fall/StructureDefinition/KontaktGesundheitseinrichtung',
      name: 'MII PR Fall Kontakt mit einer Gesundheitseinrichtung',
      module: 'Fall',
      fields: [
        'Encounter',
        'identifier',
        'status',
        'class',
        'type',
        'serviceType',
        'priority',
        'subject',
        'participant',
        'period',
        'diagnosis',
        'hospitalization',
        'location',
        'serviceProvider',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/ext/modul-biobank/StructureDefinition/Specimen',
      name: 'Profile - Specimen - Bioprobe',
      module: 'Biobank',
      fields: [
        'Specimen',
        'identifier',
        'accessionIdentifier',
        'status',
        'type',
        'subject',
        'receivedTime',
        'parent',
        'request',
        'collection',
        'processing',
        'container',
        'condition',
        'note',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/ext/modul-biobank/StructureDefinition/Organization',
      name: 'Profile - Organization - Sammlung/Biobank',
      module: 'Biobank',
      fields: [
        'Organization',
        'identifier',
        'active',
        'type',
        'name',
        'alias',
        'telecom',
        'address',
        'partOf',
        'contact',
        'endpoint',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/ext/modul-biobank/StructureDefinition/Substance',
      name: 'Profile - Substance - Additiv',
      module: 'Biobank',
      fields: [
        'Substance',
        'identifier',
        'status',
        'category',
        'code',
        'description',
        'instance',
        'ingredient',
        'substance',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/modul-consent/StructureDefinition/mii-pr-consent-einwilligung',
      name: 'Profile - MI-I - Consent - Einwilligung',
      module: 'Consent',
      fields: [
        'Consent',
        'identifier',
        'status',
        'scope',
        'category',
        'patient',
        'dateTime',
        'performer',
        'organization',
        'source',
        'policy',
        'policyRule',
        'verification',
        'provision',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/modul-consent/StructureDefinition/mii-pr-consent-documentreference',
      name: 'Profile - MI-I - Consent - DocumentReference',
      module: 'Consent',
      fields: [
        'DocumentReference',
        'masterIdentifier',
        'identifier',
        'status',
        'docStatus',
        'type',
        'category',
        'subject',
        'date',
        'author',
        'custodian',
        'description',
        'content',
        'context',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/modul-consent/StructureDefinition/mii-pr-consent-provenance',
      name: 'MII PR Consent Provenance',
      module: 'Consent',
      fields: [
        'Provenance',
        'target',
        'occurred',
        'recorded',
        'policy',
        'location',
        'reason',
        'activity',
        'agent',
        'entity',
        'signature',
      ],
    },
    {
      id: 'https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/atemwegsdruck-bei-mitl-exspiratorischem-gasfluss',
      name: 'SD MII ICU Atemwegsdruck Bei Mitl Exspiratorischem Gasfluss',
      module: 'Intensivmedizin',
      fields: [
        'Observation',
        'identifier',
        'basedOn',
        'partOf',
        'status',
        'category',
        'code',
        'subject',
        'encounter',
        'effective',
        'issued',
        'performer',
        'value',
        'interpretation',
        'device',
      ],
    },
  ]

  return profiles.map((profile, index) => {
    const parent = new ProfileEntryRelative(
      `module-${index}`,
      createDisplay(profile.module),
      `hashed-module-${index}`
    )

    const children =
      index < profiles.length - 1
        ? [
            new ProfileEntryRelative(
              profiles[index + 1].id,
              createDisplay(profiles[index + 1].name),
              `hashed-profile-${index + 1}`
            ),
          ]
        : []

    return new ProfileEntryDetails(
      profile.id,
      createDisplay(profile.name),
      profile.fields.map((field) => createDisplay(field)),
      [parent],
      children
    )
  })
}
