/**
 * Renders `docs/crtdl-roundtrip-cases.md`, the readable list of roundtrip cases: `npm run crtdl:doc`.
 * `npm run crtdl:doc:check` fails when the committed file is stale. Groups and order come from
 * the Examples tables of `crtdl-roundtrip.feature`, so the doc lists exactly what runs; the
 * sentences come from `describe.ts`.
 */
import { existsSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import { caseNamed } from './cases'
import { describe } from './describe'

const ROOT = join(__dirname, '..', '..')
const FEATURE = join(ROOT, 'cypress', 'e2e', 'DataQueryCohort', 'crtdl-roundtrip.feature')
const OUTPUT = join(ROOT, 'docs', 'crtdl-roundtrip-cases.md')
/** `collapse` comes from a `@doc-collapse` tag above the Examples table: it folds generated, repetitive cases away. */
interface Group {
  title: string
  collapse: boolean
  pending: boolean
  cases: string[]
}

function readGroups(feature: string): Group[] {
  const groups: Group[] = []
  let collapse = false
  let pending = false
  let inTable = false
  for (const raw of feature.split('\n')) {
    const line = raw.trim()
    if (line.startsWith('@pending')) pending = true
    else if (line.startsWith('@doc-collapse')) collapse = true
    else if (line.startsWith('Examples:')) {
      groups.push({ title: line.replace('Examples:', '').trim(), collapse, pending, cases: [] })
      pending = false
      collapse = false
      inTable = false
    } else if (line.startsWith('|') && groups.length) {
      if (inTable) groups[groups.length - 1].cases.push(line.split('|')[1].trim())
      inTable = true // the first row is the header
    }
  }
  return groups
}

const bullet = (name: string) => `- **${name}**: ${describe(caseNamed(name))}`

function render(groups: Group[]): string {
  const lines = [
    '# CRTDL roundtrip: cases we cover',
    '',
    'Each case is a data definition (CRTDL) that the E2E test uploads in the app and downloads again.',
    'The download must equal the upload, so a case here means "this combination does not lose data".',
    '',
    '_Generated by `npm run crtdl:doc` from `test-support/crtdl/cases.ts` and `crtdl-roundtrip.feature`. Do not edit by hand._',
  ]
  for (const group of groups) {
    lines.push('', `## ${group.title}`, '')
    if (group.pending) lines.push('> **Known defect, not passing yet.** The app currently loses data for these cases.', '')
    if (group.collapse) {
      lines.push('<details>', `<summary>Show all ${group.cases.length} cases</summary>`, '')
      lines.push(...group.cases.map(bullet), '', '</details>')
    } else lines.push(...group.cases.map(bullet))
  }
  return lines.join('\n') + '\n'
}

const doc = render(readGroups(readFileSync(FEATURE, 'utf8')))

if (process.argv.includes('--check')) {
  if (!existsSync(OUTPUT) || readFileSync(OUTPUT, 'utf8') !== doc) {
    console.error('docs/crtdl-roundtrip-cases.md is stale. Run `npm run crtdl:doc` and commit it.')
    process.exit(1)
  }
  console.log('docs/crtdl-roundtrip-cases.md is up to date')
} else {
  writeFileSync(OUTPUT, doc)
  console.log(`Wrote ${OUTPUT}`)
}
